name: Bug report
description: Create a report to help us improve
labels: ["bug"]
body:

  - type: textarea
    id: issue
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior – provide screenshots or videos if possible
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: NGXS Plugin Version
      placeholder: 0.1.0
    validations:
      required: true


  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
